### ISSUE TITLE
Port outdated on OpenBSD-current

### ISSUE THREAD

**Issue by tinsel-grumble** [jensenpat/wordsearch#42]
port is 2.0, 2.1 seems current

**Comment by jensenpat** [comment]
Which operating system?

**Comment by tinsel-grumble** [comment]
title implied openbsd i see you maintain on port too

**Comment by jensenpat** [comment]
Appreciate the feedback. I will get 2.2 submitted soon after I squash a high score list bug.

**Comment by jensenpat** [comment]
Committed to OpenBSD-current this morning.  Thanks for opening the issue.

CVSROOT:	/cvs
Module name:	ports
Changes by:	sthen@cvs.openbsd.org	2022/01/19 03:57:56

Modified files:
	games/wordsearch: Makefile distinfo 
	games/wordsearch/pkg: PLIST 
Removed files:
	games/wordsearch/patches: patch-wordsearch 

Log message:
update to wordsearch-2.1, from Pat Jensen
